# Autogenerated via tools/generate_ast.nim

import token, literalKind

type
  Expression* = ref object of RootObj
    hasError*: bool

  Binary* = ref object of Expression
    left*: Expression
    operator*: Token
    right*: Expression

  Grouping* = ref object of Expression
    expression*: Expression

  Literal* = ref object of Expression
    litString*: string
    litNumber*: float
    litBool*: bool

  Unary* = ref object of Expression
    operator*: Token
    right*: Expression

